services:
  - type: web
    name: queuecure-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: FRONTEND_URL
        value: https://queuecure-plus.vercel.app